---

- name: OCP installer
  hosts: localhost
  connection: local
#  hosts: all
  gather_facts: true
  collections:
    - community.general

  vars:
    getcert: false
    removeocp: false
    sds: false
    buildocp: false

  tasks:


    - name: Include vars of vcenter_host.yml
      ansible.builtin.include_vars:
        file: vcenter_host.yml
        name: vcenter

    - name: Include vars of server-list.yml
      ansible.builtin.include_vars:
        file: server-list.yml

    - name: Include vars of secrets.yml
      ansible.builtin.include_vars:
        file: secrets.yml
        name: secrets

    - block:
       - name: get certs
         ansible.builtin.get_url:
           url: "https://{{ vcenter.vc_fact_hostname }}.{{ vcenter.vc_fact_domain }}/certs/download.zip"
           #url: "https://{{ vcenter.vc_fact_ip }}/certs/download.zip"
           dest: ./download.zip
           validate_certs: false

       - name: Extract download.zip to /etc/pki/
         ansible.builtin.unarchive:
           src: ./download.zip
           dest: /tmp/

       - name: get files
         ansible.builtin.find:
           paths: /tmp/certs/lin/
           file_type: "file"
           patterns: "*.0"
         register: find_result

       - debug:
           msg: "{{ item.path | basename }}"
           #msg: "{{ item.path | basename }}"
         loop: "{{ find_result.files }}"

       - name: get cert into var
         ansible.builtin.set_fact:
           cert: "{{ lookup('ansible.builtin.file', '{{ item.path }}') }}"
         loop: "{{ find_result.files }}"
      when: getcert

    - block:
       - name: configure ocp
         include_tasks: ocpconfig.yml
         loop: "{{ server_list }}"

